import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "de" | "it";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.services": "Services",
    "nav.products": "Products",
    "nav.portfolio": "Portfolio",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.getAudit": "Get a Free Audit",
    
    // Hero
    "hero.headline": "Smart Systems. Scalable Growth.",
    "hero.subheadline": "From spreadsheets to software—we build what actually fits your business.",
    "hero.cta.services": "View Services",
    "hero.cta.demo": "RackleLedger Demo",
    "hero.badge": "Consult-First Digital Agency",
    "hero.stats.projects": "Projects Delivered",
    "hero.stats.satisfaction": "Client Satisfaction",
    "hero.stats.countries": "Countries Served",
    "hero.stats.experience": "Years Experience",
    
    // Decision Framework
    "decision.title": "What is your biggest hurdle?",
    "decision.subtitle": "Select your challenge and we'll guide you to the right solution.",
    "decision.messyData.title": "Internal Messy Data",
    "decision.messyData.description": "Scattered spreadsheets, duplicated entries, no single source of truth.",
    "decision.messyData.solution": "Low-Code Solutions",
    "decision.sales.title": "Need More Sales",
    "decision.sales.description": "Great product, but struggling to reach customers online.",
    "decision.sales.solution": "Web Development",
    "decision.admin.title": "Manual Admin",
    "decision.admin.description": "Spending hours on invoices, payroll, and inventory tracking.",
    "decision.admin.solution": "RackleLedger",
    
    // Services Section
    "services.title": "Our Services",
    "services.subtitle": "End-to-end digital solutions tailored to your business needs. From strategy to execution, we've got you covered.",
    "services.viewAll": "View All Services",
    "services.pageSubtitle": "End-to-end digital solutions to transform your business and accelerate growth",
    "services.learnMore": "Learn more",
    "services.cta.title": "Ready to Transform Your Business?",
    "services.cta.subtitle": "Let's discuss how our services can help you achieve your digital goals.",
    "services.cta.button": "Get a Free Consultation",
    "services.consulting.title": "Business Consulting",
    "services.consulting.description": "Strategic guidance to optimize your operations, identify growth opportunities, and navigate digital transformation.",
    "services.development.title": "Custom Software/Website Design and Development",
    "services.development.description": "Building powerful digital experiences tailored to your business needs",
    "services.marketing.title": "Digital Marketing",
    "services.marketing.description": "Driving growth through targeted marketing strategies",
    "services.branding.title": "Branding and Graphic Design",
    "services.branding.description": "Creating memorable brand identities that stand out",
    "services.design.title": "UI/UX Design",
    "services.design.description": "User-centered design that creates intuitive, engaging experiences across all digital touchpoints.",
    "services.maintenance.title": "Website Maintenance and Support",
    "services.maintenance.description": "Keeping your digital assets secure and performing optimally",
    "services.consultation.title": "Consultation and Strategy",
    "services.consultation.description": "Strategic guidance to maximize your digital presence",
    
    // Service Items
    "services.customWebDesign": "Custom Web Design",
    "services.customWebDesign.desc": "Crafting unique, visually appealing, and user-friendly websites tailored to the client's brand and audience",
    "services.responsiveDesign": "Responsive Design",
    "services.responsiveDesign.desc": "Ensuring the website looks and functions well on various devices, including desktops, tablets, and mobile phones",
    "services.uiux": "UI/UX Design",
    "services.uiux.desc": "Focusing on user interface (UI) and user experience (UX) to create intuitive and engaging user interactions",
    "services.ecommerce": "E-commerce Solutions",
    "services.ecommerce.desc": "Developing online stores with secure payment gateways, product catalogs, and shopping cart functionalities",
    "services.googleBusiness": "Google Business",
    "services.googleBusiness.desc": "Get your business registered on Google to improve local visibility and customer reach",
    "services.analytics": "Analytics and Reporting",
    "services.analytics.desc": "Using tools like Google Analytics to monitor website performance and user behavior, providing insights for continuous improvement",
    "services.customEmail": "Custom Email",
    "services.customEmail.desc": "Get custom emails for your company e.g. CEO@yourcompany.com for professional communication",
    "services.webStrategy": "Web Strategy Consulting",
    "services.webStrategy.desc": "Providing expert advice on web strategies to align with business goals",
    "services.seo": "SEO (Search Engine Optimization)",
    "services.seo.desc": "Enhancing website visibility on search engines through keyword optimization, content strategy, and technical SEO",
    "services.contentMarketing": "Content Marketing",
    "services.contentMarketing.desc": "Creating and distributing valuable content to attract and engage the target audience",
    "services.socialMedia": "Social Media Marketing",
    "services.socialMedia.desc": "Managing and growing the brand's presence on social media platforms through strategic campaigns and content",
    "services.ppc": "PPC (Pay-Per-Click) Advertising",
    "services.ppc.desc": "Running targeted advertising campaigns on platforms like Google Ads and social media to drive traffic and conversions",
    "services.emailMarketing": "Email Marketing",
    "services.emailMarketing.desc": "Developing and managing email campaigns to nurture leads and maintain customer engagement",
    "services.logoDesign": "Logo Design",
    "services.logoDesign.desc": "Creating memorable and impactful logos that represent the brand identity",
    "services.brandIdentity": "Brand Identity Design",
    "services.brandIdentity.desc": "Developing comprehensive branding elements, including color schemes, typography, and visual style guides",
    "services.graphicDesign": "Graphic Design",
    "services.graphicDesign.desc": "Designing marketing materials such as brochures, business cards, banners, and social media graphics",
    "services.regularUpdates": "Regular Updates",
    "services.regularUpdates.desc": "Keeping the website updated with the latest software and security patches",
    "services.performanceMonitoring": "Performance Monitoring",
    "services.performanceMonitoring.desc": "Tracking website performance, speed, and uptime to ensure optimal functionality",
    "services.backupRecovery": "Backup and Recovery",
    "services.backupRecovery.desc": "Implementing regular backup procedures and disaster recovery plans to protect data",
    
    // Portfolio
    "portfolio.title": "Portfolio",
    "portfolio.subtitle": "Discover how we've helped businesses transform their digital presence and streamline operations through innovative solutions.",
    "portfolio.ourWork": "Our Work",
    "portfolio.allProjects": "All Projects",
    "portfolio.softwareDev": "Software Development",
    "portfolio.webDev": "Web Development",
    "portfolio.uiuxDesign": "UI/UX Design",
    "portfolio.branding": "Branding",
    "portfolio.businessConsulting": "Business Consulting",
    "portfolio.outcome": "Outcome",
    "portfolio.cta.title": "Ready to Start Your Project?",
    "portfolio.cta.subtitle": "Let's create something amazing together. Get in touch to discuss your ideas and discover how we can help your business grow.",
    "portfolio.requestQuote": "Request a Quote",
    "portfolio.exploreServices": "Explore Our Services",
    
    // Products
    "products.title": "Innovative Software Solutions",
    "products.subtitle": "We build products that solve real business problems. Explore our suite of tools designed to streamline operations and drive growth.",
    "products.ourProducts": "Our Products",
    "products.comingSoon": "Coming Soon",
    "products.joinWaitlist": "Join the Waitlist",
    "products.learnMore": "Learn More",
    "products.moreComingSoon": "More Products Coming Soon",
    "products.moreComingSoonSubtitle": "We're constantly innovating and building new solutions. Stay tuned for more products designed to help your business thrive.",
    "products.getNotified": "Get Notified About New Products",
    "products.customSolution": "Need a Custom Solution?",
    "products.customSolutionSubtitle": "Can't find what you're looking for? We specialize in building custom software solutions tailored to your unique business needs.",
    "products.buildTogether": "Let's Build Together",
    "products.realTimeAnalytics": "Real-Time Analytics",
    "products.realTimeAnalytics.desc": "Track infrastructure costs and revenue in real-time with powerful dashboards.",
    "products.secureCompliant": "Secure & Compliant",
    "products.secureCompliant.desc": "Enterprise-grade security with full regulatory compliance built-in.",
    "products.automatedWorkflows": "Automated Workflows",
    "products.automatedWorkflows.desc": "Streamline billing, invoicing, and financial reporting automatically.",
    "products.multiTenant": "Multi-Tenant Ready",
    "products.multiTenant.desc": "Manage multiple clients and properties from a single platform.",
    
    // Contact
    "contact.title": "Contact Us",
    "contact.subtitle": "We would love to hear about your idea, new or existing project. Fill out the form below and we'll get back in touch.",
    "contact.getInTouch": "Get In Touch",
    "contact.info": "Contact Information",
    "contact.requestQuote": "Request a Quote",
    "contact.formSubtitle": "Tell us about your project and we'll provide a tailored solution.",
    "contact.firstName": "First Name",
    "contact.lastName": "Last Name",
    "contact.email": "Email Address",
    "contact.phone": "Phone Number",
    "contact.company": "Company / Organization",
    "contact.servicesNeeded": "Services Needed",
    "contact.servicesHint": "Select all the services you're interested in",
    "contact.budget": "Estimated Budget",
    "contact.selectBudget": "Select a range",
    "contact.timeline": "Project Timeline",
    "contact.selectTimeline": "Select a timeline",
    "contact.projectDetails": "Project Details",
    "contact.projectPlaceholder": "Tell us about your project, goals, and any specific requirements...",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.success": "Message sent successfully!",
    "contact.successDescription": "We'll get back to you within 24-48 hours.",
    "contact.whatNext": "What Happens Next?",
    "contact.step1": "We'll review your project details within 24 hours",
    "contact.step2": "Schedule a discovery call to discuss your needs",
    "contact.step3": "Receive a customized proposal and quote",
    "contact.location": "Location",
    "contact.servingWorldwide": "Serving clients worldwide",
    "contact.businessHours": "Business Hours",
    "contact.hours": "Mon - Fri: 9:00 AM - 6:00 PM",
    
    // About
    "about.title": "Who We Are",
    "about.subtitle": "Welcome to Rackleblock Technologies, your premier web development and digital marketing partner.",
    "about.intro": "We specialize in transforming businesses by creating powerful online presences and implementing cutting-edge digital marketing strategies.",
    "about.description": "At Rackleblock Technologies, we are passionate about helping businesses thrive in the digital world. Our team of skilled web designers, web developers, and digital marketing experts works collaboratively to deliver customized solutions that meet your unique business needs. From stunning website designs to effective SEO strategies, we ensure that your brand stands out and reaches your target audience.",
    "about.whatWeBring": "What We Bring to the Table",
    "about.skilledTeam": "Skilled Team",
    "about.skilledTeam.desc": "Web designers, developers, and marketing experts working collaboratively",
    "about.technicalExcellence": "Technical Excellence",
    "about.technicalExcellence.desc": "Cutting-edge solutions that are technically robust and scalable",
    "about.creativeDesign": "Creative Design",
    "about.creativeDesign.desc": "Visually stunning designs that capture your brand essence",
    "about.growthFocus": "Growth Focus",
    "about.growthFocus.desc": "Strategies designed to help your business thrive and expand",
    "about.targetedApproach": "Targeted Approach",
    "about.targetedApproach.desc": "Solutions customized to meet your unique business needs",
    "about.userCentric": "User-Centric",
    "about.userCentric.desc": "User-friendly experiences that engage your target audience",
    "about.mission": "Mission Statement",
    "about.missionText": "Our mission is to empower businesses of all sizes in their digital transformation journey to achieve their online goals through bespoke digital solutions that are visually stunning, user-friendly, and technically robust. We strive to build lasting partnerships with our clients by delivering exceptional value and continuously exceeding their expectations.",
    "about.vision": "Vision Statement",
    "about.visionText": "Our vision is to be a global leader in digital transformation and innovation, recognized for our creativity, technical excellence, and client-centric approach.",
    
    // Footer
    "footer.tagline": "Consult-First Digital Agency",
    "footer.copyright": "© 2024 Rackleblock Technologies. All rights reserved.",
    "footer.cta.title": "Ready to Transform Your Business?",
    "footer.cta.subtitle": "Get a free consultation and discover how we can help streamline your operations.",
    "footer.webDevelopment": "Web Development",
    "footer.digitalMarketing": "Digital Marketing",
    "footer.branding": "Branding",
    "footer.uiuxDesign": "UI/UX Design",
    "footer.allProducts": "All Products",
    "footer.company": "Company",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.imprint": "Imprint",
    
    // RackleLedger
    "rackleledger.title": "RackleLedger",
    "rackleledger.tagline": "Infrastructure-Linked Financial Management",
    "rackleledger.subtitle": "All-in-one business management for growing companies.",
    "rackleledger.description": "A B2B SaaS platform designed to revolutionize how businesses manage their infrastructure-linked finances. From real-time tracking to automated reporting, RackleLedger streamlines complex financial operations.",
    
    // RackleRush
    "racklerush.title": "RackleRush",
    "racklerush.tagline": "Viral Referral Platform",
    "racklerush.subtitle": "Turn customers into your best salesforce.",
    "racklerush.description": "Create viral referral contests that capture leads, drive engagement, and grow your customer base exponentially.",
    
    // Common
    "common.required": "required",
  },
  de: {
    // Navigation
    "nav.services": "Dienstleistungen",
    "nav.products": "Produkte",
    "nav.portfolio": "Portfolio",
    "nav.about": "Über uns",
    "nav.contact": "Kontakt",
    "nav.getAudit": "Kostenloses Audit",
    
    // Hero
    "hero.headline": "Intelligente Systeme. Skalierbares Wachstum.",
    "hero.subheadline": "Von Tabellenkalkulationen zu Software – wir bauen, was wirklich zu Ihrem Unternehmen passt.",
    "hero.cta.services": "Dienstleistungen",
    "hero.cta.demo": "RackleLedger Demo",
    "hero.badge": "Beratungsorientierte Digitalagentur",
    "hero.stats.projects": "Projekte geliefert",
    "hero.stats.satisfaction": "Kundenzufriedenheit",
    "hero.stats.countries": "Länder bedient",
    "hero.stats.experience": "Jahre Erfahrung",
    
    // Decision Framework
    "decision.title": "Was ist Ihre größte Hürde?",
    "decision.subtitle": "Wählen Sie Ihre Herausforderung und wir führen Sie zur richtigen Lösung.",
    "decision.messyData.title": "Unordentliche Daten",
    "decision.messyData.description": "Verstreute Tabellen, doppelte Einträge, keine einheitliche Datenquelle.",
    "decision.messyData.solution": "Low-Code Lösungen",
    "decision.sales.title": "Mehr Verkäufe nötig",
    "decision.sales.description": "Tolles Produkt, aber Schwierigkeiten, Kunden online zu erreichen.",
    "decision.sales.solution": "Webentwicklung",
    "decision.admin.title": "Manuelle Verwaltung",
    "decision.admin.description": "Stundenlange Arbeit mit Rechnungen, Gehaltsabrechnung und Inventar.",
    "decision.admin.solution": "RackleLedger",
    
    // Services Section
    "services.title": "Unsere Dienstleistungen",
    "services.subtitle": "End-to-End digitale Lösungen, maßgeschneidert für Ihre Geschäftsanforderungen.",
    "services.viewAll": "Alle Dienstleistungen",
    "services.pageSubtitle": "Umfassende digitale Lösungen zur Transformation Ihres Unternehmens",
    "services.learnMore": "Mehr erfahren",
    "services.cta.title": "Bereit, Ihr Unternehmen zu transformieren?",
    "services.cta.subtitle": "Lassen Sie uns besprechen, wie unsere Dienstleistungen Ihnen helfen können.",
    "services.cta.button": "Kostenlose Beratung",
    "services.consulting.title": "Unternehmensberatung",
    "services.consulting.description": "Strategische Beratung zur Optimierung Ihrer Abläufe und zur digitalen Transformation.",
    "services.development.title": "Individuelle Software-/Webentwicklung",
    "services.development.description": "Leistungsstarke digitale Erlebnisse für Ihre Geschäftsanforderungen",
    "services.marketing.title": "Digitales Marketing",
    "services.marketing.description": "Wachstum durch gezielte Marketingstrategien",
    "services.branding.title": "Branding und Grafikdesign",
    "services.branding.description": "Einprägsame Markenidentitäten, die herausstechen",
    "services.design.title": "UI/UX Design",
    "services.design.description": "Benutzerzentriertes Design für intuitive digitale Erlebnisse.",
    "services.maintenance.title": "Website-Wartung und Support",
    "services.maintenance.description": "Ihre digitalen Assets sicher und leistungsfähig halten",
    "services.consultation.title": "Beratung und Strategie",
    "services.consultation.description": "Strategische Beratung zur Maximierung Ihrer digitalen Präsenz",
    
    // Service Items
    "services.customWebDesign": "Individuelles Webdesign",
    "services.customWebDesign.desc": "Einzigartige, ansprechende und benutzerfreundliche Websites für Ihre Marke",
    "services.responsiveDesign": "Responsives Design",
    "services.responsiveDesign.desc": "Websites die auf allen Geräten perfekt funktionieren",
    "services.uiux": "UI/UX Design",
    "services.uiux.desc": "Intuitive und ansprechende Benutzerinteraktionen",
    "services.ecommerce": "E-Commerce Lösungen",
    "services.ecommerce.desc": "Online-Shops mit sicheren Zahlungssystemen und Produktkatalogen",
    "services.googleBusiness": "Google Business",
    "services.googleBusiness.desc": "Registrieren Sie Ihr Unternehmen bei Google für bessere lokale Sichtbarkeit",
    "services.analytics": "Analysen und Berichte",
    "services.analytics.desc": "Website-Performance und Benutzerverhalten überwachen",
    "services.customEmail": "Benutzerdefinierte E-Mail",
    "services.customEmail.desc": "Professionelle E-Mails wie CEO@ihrfirma.com",
    "services.webStrategy": "Web-Strategie-Beratung",
    "services.webStrategy.desc": "Expertenberatung für Webstrategien",
    "services.seo": "SEO (Suchmaschinenoptimierung)",
    "services.seo.desc": "Website-Sichtbarkeit in Suchmaschinen verbessern",
    "services.contentMarketing": "Content Marketing",
    "services.contentMarketing.desc": "Wertvolle Inhalte erstellen und verbreiten",
    "services.socialMedia": "Social Media Marketing",
    "services.socialMedia.desc": "Markenpräsenz auf sozialen Medien aufbauen",
    "services.ppc": "PPC (Pay-Per-Click) Werbung",
    "services.ppc.desc": "Gezielte Werbekampagnen auf Google und sozialen Medien",
    "services.emailMarketing": "E-Mail-Marketing",
    "services.emailMarketing.desc": "E-Mail-Kampagnen zur Kundenbindung",
    "services.logoDesign": "Logo-Design",
    "services.logoDesign.desc": "Einprägsame Logos für Ihre Markenidentität",
    "services.brandIdentity": "Markenidentität Design",
    "services.brandIdentity.desc": "Umfassende Branding-Elemente entwickeln",
    "services.graphicDesign": "Grafikdesign",
    "services.graphicDesign.desc": "Marketing-Materialien wie Broschüren und Banner",
    "services.regularUpdates": "Regelmäßige Updates",
    "services.regularUpdates.desc": "Website mit neuesten Software-Updates aktuell halten",
    "services.performanceMonitoring": "Performance-Überwachung",
    "services.performanceMonitoring.desc": "Website-Geschwindigkeit und Verfügbarkeit überwachen",
    "services.backupRecovery": "Backup und Wiederherstellung",
    "services.backupRecovery.desc": "Regelmäßige Backups und Notfallwiederherstellung",
    
    // Portfolio
    "portfolio.title": "Portfolio",
    "portfolio.subtitle": "Entdecken Sie, wie wir Unternehmen bei der digitalen Transformation unterstützt haben.",
    "portfolio.ourWork": "Unsere Arbeit",
    "portfolio.allProjects": "Alle Projekte",
    "portfolio.softwareDev": "Software-Entwicklung",
    "portfolio.webDev": "Webentwicklung",
    "portfolio.uiuxDesign": "UI/UX Design",
    "portfolio.branding": "Branding",
    "portfolio.businessConsulting": "Unternehmensberatung",
    "portfolio.outcome": "Ergebnis",
    "portfolio.cta.title": "Bereit für Ihr Projekt?",
    "portfolio.cta.subtitle": "Lassen Sie uns gemeinsam etwas Großartiges schaffen.",
    "portfolio.requestQuote": "Angebot anfordern",
    "portfolio.exploreServices": "Dienstleistungen erkunden",
    
    // Products
    "products.title": "Innovative Softwarelösungen",
    "products.subtitle": "Wir entwickeln Produkte, die echte Geschäftsprobleme lösen.",
    "products.ourProducts": "Unsere Produkte",
    "products.comingSoon": "Demnächst",
    "products.joinWaitlist": "Auf die Warteliste",
    "products.learnMore": "Mehr erfahren",
    "products.moreComingSoon": "Weitere Produkte in Kürze",
    "products.moreComingSoonSubtitle": "Wir innovieren ständig und entwickeln neue Lösungen.",
    "products.getNotified": "Über neue Produkte informiert werden",
    "products.customSolution": "Individuelle Lösung benötigt?",
    "products.customSolutionSubtitle": "Wir spezialisieren uns auf maßgeschneiderte Softwarelösungen.",
    "products.buildTogether": "Gemeinsam entwickeln",
    "products.realTimeAnalytics": "Echtzeit-Analysen",
    "products.realTimeAnalytics.desc": "Infrastrukturkosten und Einnahmen in Echtzeit verfolgen.",
    "products.secureCompliant": "Sicher & Konform",
    "products.secureCompliant.desc": "Enterprise-Sicherheit mit vollständiger Compliance.",
    "products.automatedWorkflows": "Automatisierte Workflows",
    "products.automatedWorkflows.desc": "Rechnungsstellung und Berichte automatisieren.",
    "products.multiTenant": "Mehrmandantenfähig",
    "products.multiTenant.desc": "Mehrere Kunden und Objekte von einer Plattform verwalten.",
    
    // Contact
    "contact.title": "Kontaktieren Sie uns",
    "contact.subtitle": "Wir freuen uns auf Ihre Projektidee. Füllen Sie das Formular aus und wir melden uns.",
    "contact.getInTouch": "Kontakt aufnehmen",
    "contact.info": "Kontaktinformationen",
    "contact.requestQuote": "Angebot anfordern",
    "contact.formSubtitle": "Erzählen Sie uns von Ihrem Projekt.",
    "contact.firstName": "Vorname",
    "contact.lastName": "Nachname",
    "contact.email": "E-Mail-Adresse",
    "contact.phone": "Telefonnummer",
    "contact.company": "Unternehmen / Organisation",
    "contact.servicesNeeded": "Benötigte Dienstleistungen",
    "contact.servicesHint": "Wählen Sie alle gewünschten Dienstleistungen",
    "contact.budget": "Geschätztes Budget",
    "contact.selectBudget": "Budget wählen",
    "contact.timeline": "Projektzeitplan",
    "contact.selectTimeline": "Zeitplan wählen",
    "contact.projectDetails": "Projektdetails",
    "contact.projectPlaceholder": "Erzählen Sie uns von Ihrem Projekt, Ihren Zielen und Anforderungen...",
    "contact.send": "Nachricht senden",
    "contact.sending": "Wird gesendet...",
    "contact.success": "Nachricht erfolgreich gesendet!",
    "contact.successDescription": "Wir melden uns innerhalb von 24-48 Stunden.",
    "contact.whatNext": "Was passiert als Nächstes?",
    "contact.step1": "Wir prüfen Ihre Projektdetails innerhalb von 24 Stunden",
    "contact.step2": "Wir vereinbaren einen Kennenlern-Anruf",
    "contact.step3": "Sie erhalten ein maßgeschneidertes Angebot",
    "contact.location": "Standort",
    "contact.servingWorldwide": "Wir bedienen Kunden weltweit",
    "contact.businessHours": "Geschäftszeiten",
    "contact.hours": "Mo - Fr: 9:00 - 18:00 Uhr",
    
    // About
    "about.title": "Wer wir sind",
    "about.subtitle": "Willkommen bei Rackleblock Technologies, Ihrem Partner für Webentwicklung und digitales Marketing.",
    "about.intro": "Wir sind spezialisiert auf die Transformation von Unternehmen durch leistungsstarke Online-Präsenzen und innovative digitale Marketingstrategien.",
    "about.description": "Bei Rackleblock Technologies sind wir leidenschaftlich dabei, Unternehmen in der digitalen Welt zum Erfolg zu verhelfen. Unser Team aus erfahrenen Webdesignern, Entwicklern und Marketing-Experten arbeitet gemeinsam daran, maßgeschneiderte Lösungen zu liefern.",
    "about.whatWeBring": "Was wir mitbringen",
    "about.skilledTeam": "Erfahrenes Team",
    "about.skilledTeam.desc": "Webdesigner, Entwickler und Marketing-Experten arbeiten zusammen",
    "about.technicalExcellence": "Technische Exzellenz",
    "about.technicalExcellence.desc": "Modernste Lösungen, die technisch robust und skalierbar sind",
    "about.creativeDesign": "Kreatives Design",
    "about.creativeDesign.desc": "Visuell beeindruckende Designs, die Ihre Marke verkörpern",
    "about.growthFocus": "Wachstumsfokus",
    "about.growthFocus.desc": "Strategien für das Wachstum Ihres Unternehmens",
    "about.targetedApproach": "Gezielter Ansatz",
    "about.targetedApproach.desc": "Lösungen, die auf Ihre Bedürfnisse zugeschnitten sind",
    "about.userCentric": "Benutzerzentriert",
    "about.userCentric.desc": "Benutzerfreundliche Erlebnisse für Ihre Zielgruppe",
    "about.mission": "Mission",
    "about.missionText": "Unsere Mission ist es, Unternehmen jeder Größe auf ihrem Weg der digitalen Transformation zu unterstützen. Wir liefern maßgeschneiderte digitale Lösungen, die visuell beeindruckend, benutzerfreundlich und technisch robust sind.",
    "about.vision": "Vision",
    "about.visionText": "Unsere Vision ist es, ein globaler Marktführer in der digitalen Transformation und Innovation zu sein, bekannt für Kreativität, technische Exzellenz und Kundenorientierung.",
    
    // Footer
    "footer.tagline": "Beratungsorientierte Digitalagentur",
    "footer.copyright": "© 2024 Rackleblock Technologies. Alle Rechte vorbehalten.",
    "footer.cta.title": "Bereit, Ihr Unternehmen zu transformieren?",
    "footer.cta.subtitle": "Erhalten Sie eine kostenlose Beratung.",
    "footer.webDevelopment": "Webentwicklung",
    "footer.digitalMarketing": "Digitales Marketing",
    "footer.branding": "Branding",
    "footer.uiuxDesign": "UI/UX Design",
    "footer.allProducts": "Alle Produkte",
    "footer.company": "Unternehmen",
    "footer.legal": "Rechtliches",
    "footer.privacy": "Datenschutz",
    "footer.terms": "AGB",
    "footer.imprint": "Impressum",
    
    // RackleLedger
    "rackleledger.title": "RackleLedger",
    "rackleledger.tagline": "Infrastruktur-verknüpftes Finanzmanagement",
    "rackleledger.subtitle": "All-in-One-Unternehmensverwaltung für wachsende Unternehmen.",
    "rackleledger.description": "Eine B2B-SaaS-Plattform zur Revolutionierung des Infrastruktur-Finanzmanagements. Von Echtzeit-Tracking bis zur automatisierten Berichterstellung.",
    
    // Common
    "common.required": "erforderlich",
  },
  it: {
    // Navigation
    "nav.services": "Servizi",
    "nav.products": "Prodotti",
    "nav.portfolio": "Portfolio",
    "nav.about": "Chi siamo",
    "nav.contact": "Contatti",
    "nav.getAudit": "Audit Gratuito",
    
    // Hero
    "hero.headline": "Sistemi Intelligenti. Crescita Scalabile.",
    "hero.subheadline": "Dai fogli di calcolo al software: costruiamo ciò che si adatta davvero alla tua azienda.",
    "hero.cta.services": "Vedi Servizi",
    "hero.cta.demo": "Demo RackleLedger",
    "hero.badge": "Agenzia Digitale Consulenza-First",
    "hero.stats.projects": "Progetti Consegnati",
    "hero.stats.satisfaction": "Soddisfazione Cliente",
    "hero.stats.countries": "Paesi Serviti",
    "hero.stats.experience": "Anni di Esperienza",
    
    // Decision Framework
    "decision.title": "Qual è il tuo ostacolo più grande?",
    "decision.subtitle": "Seleziona la tua sfida e ti guideremo verso la soluzione giusta.",
    "decision.messyData.title": "Dati Disordinati",
    "decision.messyData.description": "Fogli di calcolo sparsi, voci duplicate, nessuna fonte unica di verità.",
    "decision.messyData.solution": "Soluzioni Low-Code",
    "decision.sales.title": "Servono Più Vendite",
    "decision.sales.description": "Ottimo prodotto, ma difficoltà a raggiungere i clienti online.",
    "decision.sales.solution": "Sviluppo Web",
    "decision.admin.title": "Amministrazione Manuale",
    "decision.admin.description": "Ore spese su fatture, stipendi e tracciamento inventario.",
    "decision.admin.solution": "RackleLedger",
    
    // Services Section
    "services.title": "I Nostri Servizi",
    "services.subtitle": "Soluzioni digitali end-to-end su misura per le tue esigenze aziendali.",
    "services.viewAll": "Vedi Tutti i Servizi",
    "services.pageSubtitle": "Soluzioni digitali complete per trasformare la tua azienda",
    "services.learnMore": "Scopri di più",
    "services.cta.title": "Pronto a Trasformare la Tua Azienda?",
    "services.cta.subtitle": "Parliamo di come i nostri servizi possono aiutarti.",
    "services.cta.button": "Consulenza Gratuita",
    "services.consulting.title": "Consulenza Aziendale",
    "services.consulting.description": "Guida strategica per ottimizzare le operazioni e la trasformazione digitale.",
    "services.development.title": "Sviluppo Software/Web Personalizzato",
    "services.development.description": "Esperienze digitali potenti per le tue esigenze aziendali",
    "services.marketing.title": "Marketing Digitale",
    "services.marketing.description": "Crescita attraverso strategie di marketing mirate",
    "services.branding.title": "Branding e Graphic Design",
    "services.branding.description": "Identità di marca memorabili che si distinguono",
    "services.design.title": "UI/UX Design",
    "services.design.description": "Design centrato sull'utente per esperienze digitali intuitive.",
    "services.maintenance.title": "Manutenzione e Supporto Sito Web",
    "services.maintenance.description": "Mantenere i tuoi asset digitali sicuri e performanti",
    "services.consultation.title": "Consulenza e Strategia",
    "services.consultation.description": "Guida strategica per massimizzare la tua presenza digitale",
    
    // Service Items
    "services.customWebDesign": "Web Design Personalizzato",
    "services.customWebDesign.desc": "Siti web unici e user-friendly per il tuo brand",
    "services.responsiveDesign": "Design Responsive",
    "services.responsiveDesign.desc": "Siti che funzionano perfettamente su tutti i dispositivi",
    "services.uiux": "UI/UX Design",
    "services.uiux.desc": "Interazioni utente intuitive e coinvolgenti",
    "services.ecommerce": "Soluzioni E-commerce",
    "services.ecommerce.desc": "Negozi online con pagamenti sicuri e cataloghi prodotti",
    "services.googleBusiness": "Google Business",
    "services.googleBusiness.desc": "Registra la tua azienda su Google per maggiore visibilità",
    "services.analytics": "Analisi e Report",
    "services.analytics.desc": "Monitoraggio performance e comportamento utenti",
    "services.customEmail": "Email Personalizzata",
    "services.customEmail.desc": "Email professionali come CEO@tuaazienda.com",
    "services.webStrategy": "Consulenza Strategia Web",
    "services.webStrategy.desc": "Consulenza esperta per strategie web",
    "services.seo": "SEO (Ottimizzazione Motori di Ricerca)",
    "services.seo.desc": "Migliorare la visibilità del sito sui motori di ricerca",
    "services.contentMarketing": "Content Marketing",
    "services.contentMarketing.desc": "Creare e distribuire contenuti di valore",
    "services.socialMedia": "Social Media Marketing",
    "services.socialMedia.desc": "Costruire la presenza del brand sui social media",
    "services.ppc": "PPC (Pay-Per-Click)",
    "services.ppc.desc": "Campagne pubblicitarie mirate su Google e social",
    "services.emailMarketing": "Email Marketing",
    "services.emailMarketing.desc": "Campagne email per fidelizzazione clienti",
    "services.logoDesign": "Design Logo",
    "services.logoDesign.desc": "Loghi memorabili per la tua identità di marca",
    "services.brandIdentity": "Design Identità di Marca",
    "services.brandIdentity.desc": "Sviluppo completo degli elementi del brand",
    "services.graphicDesign": "Graphic Design",
    "services.graphicDesign.desc": "Materiali marketing come brochure e banner",
    "services.regularUpdates": "Aggiornamenti Regolari",
    "services.regularUpdates.desc": "Mantenere il sito aggiornato con gli ultimi software",
    "services.performanceMonitoring": "Monitoraggio Performance",
    "services.performanceMonitoring.desc": "Monitorare velocità e uptime del sito",
    "services.backupRecovery": "Backup e Ripristino",
    "services.backupRecovery.desc": "Backup regolari e piani di disaster recovery",
    
    // Portfolio
    "portfolio.title": "Portfolio",
    "portfolio.subtitle": "Scopri come abbiamo aiutato le aziende nella trasformazione digitale.",
    "portfolio.ourWork": "I Nostri Lavori",
    "portfolio.allProjects": "Tutti i Progetti",
    "portfolio.softwareDev": "Sviluppo Software",
    "portfolio.webDev": "Sviluppo Web",
    "portfolio.uiuxDesign": "UI/UX Design",
    "portfolio.branding": "Branding",
    "portfolio.businessConsulting": "Consulenza Aziendale",
    "portfolio.outcome": "Risultato",
    "portfolio.cta.title": "Pronto per il Tuo Progetto?",
    "portfolio.cta.subtitle": "Creiamo qualcosa di straordinario insieme.",
    "portfolio.requestQuote": "Richiedi Preventivo",
    "portfolio.exploreServices": "Esplora i Servizi",
    
    // Products
    "products.title": "Soluzioni Software Innovative",
    "products.subtitle": "Costruiamo prodotti che risolvono problemi aziendali reali.",
    "products.ourProducts": "I Nostri Prodotti",
    "products.comingSoon": "Prossimamente",
    "products.joinWaitlist": "Iscriviti alla Lista d'Attesa",
    "products.learnMore": "Scopri di Più",
    "products.moreComingSoon": "Altri Prodotti in Arrivo",
    "products.moreComingSoonSubtitle": "Stiamo costantemente innovando e sviluppando nuove soluzioni.",
    "products.getNotified": "Ricevi Notifiche sui Nuovi Prodotti",
    "products.customSolution": "Serve una Soluzione Personalizzata?",
    "products.customSolutionSubtitle": "Siamo specializzati in soluzioni software su misura.",
    "products.buildTogether": "Costruiamo Insieme",
    "products.realTimeAnalytics": "Analisi in Tempo Reale",
    "products.realTimeAnalytics.desc": "Traccia costi e ricavi dell'infrastruttura in tempo reale.",
    "products.secureCompliant": "Sicuro e Conforme",
    "products.secureCompliant.desc": "Sicurezza enterprise con conformità normativa completa.",
    "products.automatedWorkflows": "Workflow Automatizzati",
    "products.automatedWorkflows.desc": "Automatizza fatturazione e reportistica.",
    "products.multiTenant": "Multi-Tenant",
    "products.multiTenant.desc": "Gestisci più clienti e proprietà da un'unica piattaforma.",
    
    // Contact
    "contact.title": "Contattaci",
    "contact.subtitle": "Ci piacerebbe sentire la tua idea di progetto. Compila il modulo e ti ricontatteremo.",
    "contact.getInTouch": "Mettiti in Contatto",
    "contact.info": "Informazioni di Contatto",
    "contact.requestQuote": "Richiedi Preventivo",
    "contact.formSubtitle": "Parlaci del tuo progetto.",
    "contact.firstName": "Nome",
    "contact.lastName": "Cognome",
    "contact.email": "Indirizzo Email",
    "contact.phone": "Numero di Telefono",
    "contact.company": "Azienda / Organizzazione",
    "contact.servicesNeeded": "Servizi Richiesti",
    "contact.servicesHint": "Seleziona tutti i servizi che ti interessano",
    "contact.budget": "Budget Stimato",
    "contact.selectBudget": "Seleziona un range",
    "contact.timeline": "Tempistiche Progetto",
    "contact.selectTimeline": "Seleziona tempistiche",
    "contact.projectDetails": "Dettagli Progetto",
    "contact.projectPlaceholder": "Parlaci del tuo progetto, obiettivi e requisiti specifici...",
    "contact.send": "Invia Messaggio",
    "contact.sending": "Invio in corso...",
    "contact.success": "Messaggio inviato con successo!",
    "contact.successDescription": "Ti risponderemo entro 24-48 ore.",
    "contact.whatNext": "Cosa Succede Dopo?",
    "contact.step1": "Esamineremo i dettagli del tuo progetto entro 24 ore",
    "contact.step2": "Fisseremo una chiamata conoscitiva",
    "contact.step3": "Riceverai una proposta personalizzata",
    "contact.location": "Sede",
    "contact.servingWorldwide": "Serviamo clienti in tutto il mondo",
    "contact.businessHours": "Orari di Lavoro",
    "contact.hours": "Lun - Ven: 9:00 - 18:00",
    
    // About
    "about.title": "Chi Siamo",
    "about.subtitle": "Benvenuti a Rackleblock Technologies, il vostro partner per sviluppo web e marketing digitale.",
    "about.intro": "Siamo specializzati nella trasformazione delle aziende attraverso presenze online potenti e strategie di marketing digitale innovative.",
    "about.description": "A Rackleblock Technologies, siamo appassionati di aiutare le aziende a prosperare nel mondo digitale. Il nostro team di web designer, sviluppatori ed esperti di marketing lavora insieme per fornire soluzioni personalizzate.",
    "about.whatWeBring": "Cosa Offriamo",
    "about.skilledTeam": "Team Esperto",
    "about.skilledTeam.desc": "Web designer, sviluppatori ed esperti di marketing che lavorano insieme",
    "about.technicalExcellence": "Eccellenza Tecnica",
    "about.technicalExcellence.desc": "Soluzioni all'avanguardia tecnicamente robuste e scalabili",
    "about.creativeDesign": "Design Creativo",
    "about.creativeDesign.desc": "Design visivamente impressionanti che catturano l'essenza del brand",
    "about.growthFocus": "Focus sulla Crescita",
    "about.growthFocus.desc": "Strategie progettate per far prosperare la tua azienda",
    "about.targetedApproach": "Approccio Mirato",
    "about.targetedApproach.desc": "Soluzioni personalizzate per le tue esigenze",
    "about.userCentric": "Centrato sull'Utente",
    "about.userCentric.desc": "Esperienze user-friendly per il tuo pubblico target",
    "about.mission": "Mission",
    "about.missionText": "La nostra missione è supportare aziende di ogni dimensione nel loro percorso di trasformazione digitale. Forniamo soluzioni digitali su misura che sono visivamente impressionanti, user-friendly e tecnicamente robuste.",
    "about.vision": "Vision",
    "about.visionText": "La nostra visione è essere un leader globale nella trasformazione digitale e innovazione, riconosciuti per creatività, eccellenza tecnica e approccio centrato sul cliente.",
    
    // Footer
    "footer.tagline": "Agenzia Digitale Consulenza-First",
    "footer.copyright": "© 2024 Rackleblock Technologies. Tutti i diritti riservati.",
    "footer.cta.title": "Pronto a Trasformare la Tua Azienda?",
    "footer.cta.subtitle": "Ottieni una consulenza gratuita.",
    "footer.webDevelopment": "Sviluppo Web",
    "footer.digitalMarketing": "Marketing Digitale",
    "footer.branding": "Branding",
    "footer.uiuxDesign": "UI/UX Design",
    "footer.allProducts": "Tutti i Prodotti",
    "footer.company": "Azienda",
    "footer.legal": "Legale",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Termini di Servizio",
    "footer.imprint": "Imprint",
    
    // RackleLedger
    "rackleledger.title": "RackleLedger",
    "rackleledger.tagline": "Gestione Finanziaria Infrastrutturale",
    "rackleledger.subtitle": "Gestione aziendale all-in-one per aziende in crescita.",
    "rackleledger.description": "Una piattaforma B2B SaaS progettata per rivoluzionare la gestione finanziaria infrastrutturale. Dal tracking in tempo reale alla reportistica automatizzata.",
    
    // Common
    "common.required": "obbligatorio",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const path = window.location.pathname;
      if (path.startsWith("/de")) return "de";
      if (path.startsWith("/it")) return "it";
    }
    return "en";
  });

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
